- docs/_templates/page.njk
Move the skip link to above the header as this should be the first
thing that is focusable.
> [refs #106] Move skip link to above the header

- .travis.yml
By default, travis will clean up all artefacts left over from npm install which means the `npm publish` command fails.
We need to specify `skip_cleanup: true` as we have done in the other jobs.
> Skip cleanup before publishing npm package

- packages/components/header/_header.scss
- packages/core/settings/_globals.scss
- The header spacing was 16px and the original design is 20px.
- A variable `$nhsuk-header-spacing` has been added to /core/settings.
- Removed extra margin from nav list.
- Added border to nav list to create a divider between the breadcrumb.
> [refs #57] Refactored header spacing

- docs/contributing/coding-standards/html.md
Fix the markdown so HTML displays properly
> [refs #133] Remove extra backtick in HTML readme

- packages/components/header/_header.scss
Looking at the main navigation links in high contrast view on Windows,
the yellow outline border is not seen when using the keyboard to
navigate to them and bringing them into focus. To make them standout
and give a visual clue as to where you are, they should be underlined
when in focus.
> [refs #107] Add underline when focus on main navigation items

- packages/components/details/_details.scss
To avoid having to configure asset paths in the build for 1 icon,
we have base64 encoded the icon and put it as the background image.
In general this is bad practice so we will need to revisit this.
> [refs #107] Expander SVG background image base64

- packages/components/details/_details.scss
Instead of base64 encoding the SVG icon, just encode the SVG
icon using https://yoksel.github.io/url-encoder/
> refs #107] Expander SVG background image

- tasks/docs.js
By default, the gulp-connect server is restricted to serving over
localhost. We add a host setting to allow all IP addresses.
> Allow the dev server over external IP

- packages/components/do-dont-list/README.md
- packages/components/do-dont-list/template.html
- packages/components/do-dont-list/template.njk
- packages/core/styles/_lists.scss
Rename nhsuk-list--check to nhsuk-list--tick to be more consistent
Add optional heading level parameter
> [refs #164] Rename check list to tick, update Nunjucks parameters

- docs/components/care-card-immediate.njk
- docs/components/care-card-non-urgent.njk
- docs/pages/examples.njk
- packages/components/care-card/README.md
- packages/components/care-card/_care-card.scss
- packages/components/care-card/template.html
- packages/components/care-card/template.njk
- packages/core/tools/_mixins.scss
Emergency care card now called immediate care card
Update Nunjucks template and parameters
Add correct hidden text
Amend visually hidden style to fix VoiceOver issue
> [refs #160] Rename and updates to care cards

- docs/components/contents-list.njk
- packages/components/contents-list/README.md
- packages/components/contents-list/template.html
- packages/components/contents-list/template.njk
The aria-current on the <span> causes a weird VoiceOver issue on
MacOS where it seems to make VoiceOver hang when using the 'read all'
command. So, the aria-current is moved to the `<li>` element.
Updates to the Nunjucks arguments table.
> [refs #161] Fix MacOS VoiceOver issue and Nunjucks updates

- packages/components/action-link/template.njk
- packages/components/do-dont-list/template.njk
- packages/components/header/template.njk
- packages/components/list-panel/template.njk
- packages/components/pagination/template.njk
When trying to use the nunjucks macros using npm, the paths for
the SVG includes were broken because they were absolute paths. using
SVG inline icons fixes this issue.
> [refs #107] Remove SVG includes to fix npm usage

- packages/components/footer/README.md
- packages/components/footer/template.html
- packages/components/footer/template.njk
Add aria-label and remove visually hidden text to logo href.
Update to Nunjucks parameters and associated README information.
> [refs #168] Update to Nunjucks implementation and aria addition

- CHANGELOG.md
Start a CHANGELOG so that we can document our changes between
releases and include any breaking changes for users to be able
to see actions they need to take.
> Add CHANGELOG to document our changes between releases

- docs/components/all.njk
- packages/components/feedback-banner/_feedback-banner.scss
- packages/components/feedback-banner/feedback-banner.js
- packages/components/footer/template.njk
Accessibility fix to not obscure the footer with the banner, by
repositioning it to below the footer when it comes in to view. The
contents of the banner are also keyboard navigable when this happens.
> [refs #167] Amend banner to not be sticky when footer is scrolled to

- packages/components/back-link/README.md
- packages/components/error-summary/README.md
The HTML markup for the back link and error summary were wrong,
they have been updated to reflect the correct markup.
> [refs #206] Fix incorrect back link and error summary examples

- packages/assets/icons/icon-emdash-small.svg
- packages/assets/icons/icon-emdash.svg
- packages/components/contents-list/_contents-list.scss
- packages/core/styles/_icons.scss
The em-dash added content in css is read out in screen readers so
have changed it to an svg background image.
> [refs #161] Change em-dash content to background svg

- CHANGELOG.md
- packages/components/care-card/README.md
- packages/components/care-card/_care-card.scss
- packages/components/care-card/template.html
- packages/components/care-card/template.njk
- packages/core/tools/_mixins.scss
Using the clip path method for generating the care card triangles makes
it not show up in High Contrast Mode in Windows. This was picked up in a
DAC report. Despite looking at a gov.uk blog post on this
(https://accessibility.blog.gov.uk/2018/08/01/supporting-users-who-change-colours-on-gov-uk/)
it still didn't seem to work in High Contrast Mode, so it has been
changed to borders and transforms, inspired from
https://codepen.io/mpeace/pres/eBOVGe
> [refs #160] Change the way triangle is generated in care cards

- CHANGELOG.md
The old prefix class name was incorrect, used the correct class name
so its easier for people to update their projects.
> [refs #107] Fix a typo in the CHANGELOG for nhsuk-u- prefix

- CHANGELOG.md
- package.json
- packages/components/feedback-banner/feedback-banner.js
If the feedback banner element did not exist on the page, the JavaScript console in browsers would throw an error when users were scrolling down the page because it couldn't find that element.
> [refs #107] Fix feedback banner JS to prevent console errors

- packages/components/care-card/README.md
Add a para of text to red (urgent) care card.
Delete hyperlink from red and black (immediate) care card. 
Add H2 for Guidance to make link to service manual more prominent.
> Align care card with service manual

- docs/pages/about.njk
Fix the link in the about page to the contributing guideline
> Fix contributing guideline link

- docs/_templates/page.njk
- docs/pages/about.njk
- docs/pages/install.njk
The NHS logo was linking to a broken page on GitHub pages, it should link back to the NHS.UK website. Also the contact us address has been changed to the standards email and slack channel.
> Fix broken NHS logo link and update the contact us address

- docs/pages/examples.njk
A very small PR to fix routing bug in the docs for the Example page, which I noticed after seeing this repo on HN.
Feel free to close the PR if it's being fixed elsewhere, just bugged me
> Docs/Homepage link routing from the examples page.

- packages/components/error-summary/_error-summary.scss
- packages/components/radios/_radios.scss
- packages/components/skip-link/_skip-link.scss
- packages/core/tools/_mixins.scss
Used the term 'has focus' rather than 'focused' (or 'focussed').
> Update use of 'focused' in documentation

- CHANGELOG.md
- packages/components/button/README.md
- packages/components/button/_button.scss
- packages/components/button/template.njk
Add options in Nunjucks template to allow for button to be also either
an <a> or <input> element.
Update css accordingly to take account of allowing <a> and <input>
Update README regarding attribute order in HTML example.
> [refs #296] Allow button to be an <a> or <input>

- package-lock.json
- packages/assets/icons/icon-minus.svg
- packages/assets/icons/icon-plus.svg
- packages/assets/icons/icon-tick.svg
- packages/components/details/_details.scss
- packages/components/do-dont-list/README.md
- packages/components/do-dont-list/template.njk
- packages/core/styles/_icons.scss
The wrong blue was being used for the expander, plus and minus icons.
Also the tick icon stroke colour was not displaying properly in preview.
> Use the correct NHS blue for plus and minus icons

- packages/components/inset-text/README.md
Change sentence in example to say "You can report any suspected side effect to the UK safety scheme [link]." Old sentence about vertigo didn't reflect practice on nhs.uk. New sentence is an example of current usage.
In line with service manual example.
> Change content in example

- packages/components/radios/README.md
Remove the `'` character from the nunjucks example id and modify the corresponding HTML output
> Fix typo in radios example readme

- app/components/radios/inline.njk
- docs/installation/installing-compiled.md
- packages/components/breadcrumb/README.md
- packages/components/breadcrumb/template.njk
- packages/components/checkboxes/README.md
- packages/components/footer/README.md
- packages/components/header/README.md
- packages/components/header/template.njk
- packages/components/hero/README.md
- packages/components/hero/template.njk
- packages/components/input/README.md
- packages/components/list-panel/README.md
- packages/components/list-panel/template.njk
- packages/components/pagination/README.md
- packages/components/panel/README.md
- packages/components/panel/template.njk
- packages/components/promo/README.md
- packages/components/promo/template.njk
- packages/components/radios/README.md
- packages/components/radios/template.njk
- packages/components/select/README.md
- packages/components/textarea/README.md
- Update installing with compiled documentation page template with skip link, header and footer components.
- Remove white space and empty lines from nunjucks templates and make sure that each component HTML snippets match the nunjuck example.
- Make sure that each of the HTML snippets work using compiled files rather than npm package.
- Header HTML snippet was missing the new autocomplete `<div>`
- Pagination HTML snippet was using the old class name for the visually hidden utility class
- Add missing closing `</div>` to the promo HTML snippet.
> Update components HTML snippet to match nunjucks templates

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- CONTRIBUTING.md
Was because it was capital .MD instead of .md, also fixed the bug emoji should be in unicode rather than classic emoji form.
> Fix broken code of conduct link and bug issue emoji

- packages/components/review-date/README.md
- packages/components/review-date/template.njk
Removed the <time> element around the review dates because it fails
validation without a datetime attribute, which cannot be automatically
generated (yet) from the date value. Even though datetime attribute is
not strictly necessary, this can only be the case if the review date
entered is a valid date or time string, which cannot be guaranteed.
More info here:
https://www.w3.org/TR/2011/WD-html5-author-20110705/the-time-element.html
> [refs #177] Remove <time> element

- app/components/fieldset/with-inputs.njk
- app/pages/examples.njk
- packages/components/fieldset/README.md
So that input fields can be put inside the fieldset, you can use the
'call' block:
https://mozilla.github.io/nunjucks/templating.html#call
> [refs #385] Document the 'call' block for fieldset

- packages/components/panel/_panel.scss
When using a shorter amount of content within a panel group component, the panel does not fill the full width of the grid item. The panel should fill the width of the grid item rather than just the width of content.
https://github.com/nhsuk/nhsuk-frontend/issues/395
> [refs #395] Panel component should fill the width of the grid item

- CHANGELOG.md
- package-lock.json
- package.json
- packages/core/README.md
- packages/core/objects/_width-container.scss
The current nhsuk-width-container is restricted to a max width of 960px. A new container has been added (nhsuk-width-container-fluid), which which spans the entire width of the viewport and allows for full-screen layouts.
**To Do:**
Just in process of writing up the documentation for the service manual, should be ready before we release 2.10.
> [refs #416] Extend the page layout to include a fluid-width container.

- CHANGELOG.md
- packages/components/error-message/README.md
- packages/components/error-message/template.njk
Prefix error messages with a visually hidden "Error:", to make it clearer to users of assistive technologies.
> Prefix error messages with hidden "Error:"

- app/components/tables/tables-panel.njk
Changed heading to "Conditions similar to impetigo", caption to "Other possible causes of your symptoms" and first column to "Symptoms".
Previously, screenreaders will have read out the same line "Skin symptoms and possible causes" twice (as heading and caption).
> Made distinction between heading and caption

- CHANGELOG.md
- app/components/date-input/autocomplete.njk
- app/components/input/autocomplete.njk
- app/components/textarea/autocomplete.njk
- app/pages/examples.njk
- packages/components/date-input/README.md
- packages/components/date-input/template.njk
- packages/components/input/README.md
- packages/components/input/template.njk
- packages/components/textarea/README.md
- packages/components/textarea/template.njk
This was already possible to do with the `attributes` option but this change highlights the new WCAG 2.1 success criteria (Identify Input Purpose) which "is to ensure that the purpose of a form input collecting information about the user can be programmatically determined, so that user agents can extract and present this purpose to users using different modalities".
See [autofilling form controls: the autocomplete attribute](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill) for the full list of attributes that can be used.
Added a note about the `pattern` attribute being used alongside `type="number"` due to invalid HTML being used.
> Enable autocomplete attributes for input components

- CHANGELOG.md
- packages/components/header/_autocomplete.scss
- packages/core/generic/_font-face.scss
- packages/core/settings/_globals.scss
The Frutiger light font was only being referenced in the header
autocomplete dropdown, so we've decided to remove it and save a request
to get it.
> Remove light version of the font

- docs/installation/installing-with-npm.md
remove duplicate favicons from the installing with npm docs.
> remove the duplicate favicons from the docs

- CHANGELOG.md
- package-lock.json
- package.json
- packages/core/README.md
- packages/core/styles/_typography.scss
Lede text styling for use after the `<h1>` element, often used as intro text for the page immediately following the page header.
You can see an example of Lede text on the [NHS website Live Well page](https://www.nhs.uk/live-well/), you can find the HTML code for Lede text in the [Typography section in the README](https://github.com/nhsuk/nhsuk-frontend/blob/master/packages/core#lede-text). ([Issue 106](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/106))
> [refs #474] lede text styling and example of markup

- CHANGELOG.md
- packages/core/README.md
- packages/core/utilities/_typography.scss
Secondary text colour utility class - a new utility class to be able to use the secondary text colour within elements (`$nhsuk-secondary-text-color` - `#425563`) 
You can find the HTML code for secondary text colour utility class in the [Utilities section in the README](https://github.com/nhsuk/nhsuk-frontend/blob/master/packages/core#secondary-text-colour) ([Issue 465](https://github.com/nhsuk/nhsuk-frontend/issues/465))
> [refs #465] secondary text colour utility class

- packages/components/panel/README.md
fixed the panel group to contain 2 panels within the nhsuk-grid-row nhsuk-panel-group div and not 4.
> update panel group nunjuck macro

- docs/installation/installing-compiled.md
Update the example HTML layout to be filled in with the absolute URL.
CHANGELOG entry not needed as its a fix for a previous entry.
> open graph image asset path should be an absolute url

- CHANGELOG.md
- docs/contributing/coding-standards.md
- packages/components/checkboxes/_checkboxes.scss
- packages/components/details/_details.scss
- packages/components/radios/_radios.scss
There are three places in where &s are used in the middle of selectors.
These instances have been rewritten to remove these and separate them
out into separate selectors, so that the NHSUK styles can be used in
conjunction with existing external selectors.
> Patch to remove &s from the middle of selectors.

- CHANGELOG.md
- packages/components/details/_details.scss
This is for Issue #486
After a details component the next h2 / nhsuk-heading-l  has additional padding
> h2 additional padding top after details component

- CHANGELOG.md
- package-lock.json
- package.json
- packages/components/details/_details.scss
Fix an issue on Microsoft Edge with the sizing of the +/- icons overlapping the title of the Expander.
See my comment on the issue for the explanation of the issue: https://github.com/nhsuk/nhsuk-frontend/issues/508#issuecomment-514608421
#508
> fix issue with the expander icon sizing on Edge

- .travis.yml
- unpin the specific version of the BackstopJS docker image in Travis CI config 
- remove the Slack notification in the Travis CI config
> use the latest version of backstopjs in the travis config

- package.json
Code editors weren't automatically picking up the configuration file for the eslint, added to package.json so that they know where to look.
> add eslint and sass lint configuration path for code editors

- CHANGELOG.md
Changes to the documentation or our GitHub example pages don't require a changelog entry (only changes that will affect end-users applications) also fixed a broken link to a GitHub issue.
> remove entry to a documentation change and fix broken issue link

- CHANGELOG.md
- package-lock.json
- package.json
- packages/components/details/details.polyfill.js
- packages/components/header/_autocomplete.scss
- packages/components/header/autocomplete.js
Added linting to all JavaScript files under `packages/components`
Removed linting from details polyfill as it isn't our code... this will be fixed soon with ES6 refactor
Fixed linting errors in autocomplete
Added check for header search element to prevent JS error when adding and event listener
Removed unnecessary JavaScript which positioned the autocomplete on resize
Refactored CSS to position the autocomplete without the need for JavaScript
> Fix javascript error with when header search is not present

- CONTRIBUTING.md
- README.md
- app/pages/about.njk
The invite URL for the service manual Slack workspace had expired so people could no longer join the workspace using the link. A new invite URL has been generated.
Doesn't need a change log entry as its just a change to the frontend docs.
> update the expired service manual Slack invite URL

- docs/contributing/automated-testing.md
- package.json
Add npm script to approve BackstopJS reference screenshots. After running BackstopJS tests you can update the screenshots with `npm run backstop:approve` opposed to having to run the tests again.
Change log not required as its doesn't affect the package.
> Add npm script to approve BackstopJS screenshot changes

- CHANGELOG.md
- packages/components/fieldset/_fieldset.scss
Removing `overflow: hidden` hack for hint text in fieldsets
> Removing overflow hidden hack

- CHANGELOG.md
- packages/core/settings/_globals.scss
Changed `$nhsuk-font-fallback: Helvetica, Arial, Sans-serif;` to `$nhsuk-font-fallback: Arial, Sans-serif;`
> Set fallback font to Arial by removing Helvetica

- package-lock.json
Create new package-lock.json using Node.js v12.13.0 as it is the LTS release as of 21/10/2019.
Without this fix the package doesn't install the node-sass binaries when using Node v12.x
I will bump my changelog and versions after discussing the planned order of release with other PRs.
> Update package-lock to build on new Node LTS

- CHANGELOG.md
- package.json
- packages/components/details/details.js
Keydown events for space and enter were not opening or closing the details component. They now call the click event which works as expected.
> Call click event on keydown event

- CHANGELOG.md
- docs/installation/installing-compiled.md
- package-lock.json
- packages/components/header/README.md
- packages/components/header/template.njk
Change header search defaults so that they use nhs.uk search. 
Form action is now `https://www.nhs.uk/search/`
The input name is now `q`
resolves #552
> Default search params

- README.md
Priorities with the NuGet and PyPi packages for the NHS.UK frontend have changed, they are currently in development but aren't ready so removing the reference to them to avoid confusion.
> remove references to the NuGet and PyPi packages until they are finished

- packages/core/tools/_typography.scss
Warning about deprecated feature in sass. `@else if` is supported going forward and not `@elseif`
'DEPRECATION WARNING on line 148, column 7 of node_modules/nhsuk-frontend/packages/core/tools/_typography.scss: 
elseif is deprecated and will not be supported in future Sass versions.'
Updated core/tools/_typography.css to remove use of deprecated feature.
> @elseif unsupported in future versions of sass

- CHANGELOG.md
- package-lock.json
- package.json
- packages/components/details/_details.scss
Internet Explorer 11 requires both the width and height to be set for SVG background images.
[Sizing SVG background images in Internet Explorer
](https://thatemil.com/blog/2015/03/15/sizing-svg-background-images-in-internet-explorer/)
resolves #564
> fix the Expander plus and minus icon sizing on IE11

- CHANGELOG.md
- packages/components/back-link/_back-link.scss
- packages/components/breadcrumb/_breadcrumb.scss
- packages/components/button/_button.scss
- packages/components/pagination/_pagination.scss
Fix some pseudo link styles for the:
- button as a link (text colour for the active state)
- back link (text colour for the visited/hover state)
- breadcrumb (text colour for the visited/hover state)
- pagination (icon colour for the visited/hover state)
> Fix link styles

- CHANGELOG.md
- packages/components/header/_header.scss
On screen sizes between the table and large-desktop breakpoints, there is a random 1 pixel margin-top on the Menu button in Safari. This makes the button unaligned with the search bar.
This isn't an issue on Chrome or Firefox
Setting margin-top to 0 between the table and large-desktop breakpoints fixes the issue on Safari and has no affect on other browsers.
> remove random margin-top from the Menu button on Safari

- CHANGELOG.md
- packages/components/care-card/_care-card.scss
Prevent additional padding on care card headings. This helps if the care card is nested within multiple sections or divs and the general padding removal doesn't apply.
> prevent additional padding on care card headings

- README.md
- app/index.njk
- packages/components/action-link/README.md
- packages/components/back-link/README.md
- packages/components/breadcrumb/README.md
- packages/components/button/README.md
- packages/components/care-card/README.md
- packages/components/checkboxes/README.md
- packages/components/contents-list/README.md
- packages/components/date-input/README.md
- packages/components/details/README.md
- packages/components/do-dont-list/README.md
- packages/components/error-message/README.md
- packages/components/error-summary/README.md
- packages/components/fieldset/README.md
- packages/components/footer/README.md
- packages/components/header/README.md
- packages/components/hint/README.md
- packages/components/images/README.md
- packages/components/input/README.md
- packages/components/inset-text/README.md
- packages/components/pagination/README.md
- packages/components/radios/README.md
- packages/components/review-date/README.md
- packages/components/select/README.md
- packages/components/skip-link/README.md
- packages/components/tables/README.md
- packages/components/textarea/README.md
- packages/components/warning-callout/README.md
The NHS digital service manual recently went from beta to live. This change is up date all the links to the service manual in the documentation.
> update links to the latest service manual URL

- .travis.yml
Travis CI was having issues deploying to npm due to recently version changes in tooling on their end. This change opts in to using the latest version and relevant configuration for the new token name for API keys.
https://docs.travis-ci.com/user/deployment-v2
https://travis-ci.community/t/missing-api-key-when-deploying-to-github-releases/5761/14
> fix issue with Travis CI by opting into v2 deployment tooling

- CHANGELOG.md
- packages/components/breadcrumb/_breadcrumb.scss
Resolves: #589 
Following the instructions on issue #589, added a `:focus:hover` state and made it `$nhsuk-focus-text-color`.
I wasn't sure what format would be preferred. I went with the latter, and both seemed to pass the linting checks.
```scss
:focus:hover {
}
// or 
:focus {
:hover {
}
}
```
There didn't seem to be a new release planned in the CHANGELOG, and I didn't want to presume what type of release and the date, so happy to take advice on this.
> Added focus-text-color to the breadcrumb on :focus:hover

- CHANGELOG.md
- packages/components/button/README.md
- packages/components/button/_button.scss
- packages/components/button/template.njk
Button - fix the text colour on :focus :visited states and remove the role="button" from button as a link example ([Issue 593](https://github.com/nhsuk/nhsuk-frontend/issues/593)) ([Issue 425](https://github.com/nhsuk/nhsuk-frontend/issues/425))
Resolves #593 & #425
> Button - fix the text colour on :focus :visited states

- CHANGELOG.md
- packages/core/tools/_links.scss
Fix the styles for the `nhsuk-link-style-white`
> Fix link style white

- CHANGELOG.md
- packages/components/breadcrumb/_breadcrumb.scss
> Fix breadcrumb link focus colour when link has been visited

- app/components/warning-callout/custom-heading.njk
- packages/components/warning-callout/template.njk
Change the `{%- if params.heading != "Important" %}` to `{%- if "Important" in params.heading %}` so the hidden text of 'Important' does not show if a custom header includes the word important, for example 'Important Coronavirus update'
For example:
> Update warning callout template.njk

- CHANGELOG.md
- jest.config.js
- packages/components/header/headerAutoComplete.js
- packages/components/header/template.njk
Adding in the ability to set search URLs as variables on the window to override the hardcoded variables defined in headerAutoComplete.js. This looks for an override and if there's nothing there will default to use the funnelback URL.
> Search api update

- CHANGELOG.md
- packages/components/checkboxes/README.md
- packages/components/date-input/README.md
- packages/components/hint/README.md
- packages/components/hint/template.njk
- packages/components/input/README.md
- packages/components/radios/README.md
- packages/components/select/README.md
- packages/components/textarea/README.md
Changed Hint component to use div rather than span to allow for multi-line elements within hints. Updated docs and changelog.
> Multi-line hints

- docs/installation/installing-compiled.md
- packages/assets/logos/logo-nhs.svg
- packages/components/header/README.md
- packages/components/header/template.njk
Add the xlink namespace to address the 'Unbound namespace prefix: "xlink"' error.
The SVG is currently not valid.
> Ensure logo-nhs.svg is a valid SVG file.

- CHANGELOG.md
- package-lock.json
- packages/components/date-input/README.md
- packages/components/date-input/template.njk
- packages/components/input/README.md
- packages/components/input/template.njk
Add `inputmode` and `spellcheck` options to Text input component Nunjucks macro.
Change `type="number"` to `inputmode="numeric"` on the Date input component.
- https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/293
- https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/223
- https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/10
> Swap input type number with inputmode numeric - Text and Date input

- CHANGELOG.md
- packages/components/header/autoCompleteConfig.js
- packages/components/header/headerAutoComplete.js
On Android Chrome you cannot go to a search results page by touching a header search suggestion.
This is because of the `accessible-autocomplete` package blocking this event. They offer an `onConfirm` callback which is called on touch, click or enter on a focused option.
Dev has been completed to add this callback to our `headerAutoComplete`
> Android Chrome search suggestions bug

- CHANGELOG.md
- packages/components/details/_details.scss
In Internet Explorer 10, the expander icons are squished somewhat. They are still functional and technically this might be considered graceful degradation, but the fix is relatively simple and doesn't have any side effects to my knowledge, so I think it's probably worth fixing.
Here's how it looks currently:
and after the fix in IE10:
> Set width and height on expander SVG images to avoid squashed display in IE10

- app/_templates/layout.njk
- app/_templates/page.njk
- package.json
- tasks/docs.js
Fix the URLs that "Install", "Examples" and "About" footer links direct to.
> Fix Install, Examples and About footer link URLs

- CHANGELOG.md
- package-lock.json
- package.json
- packages/core/tools/_sass-mq.scss
- packages/core/vendor/sass-mq.scss
We're trying to use NHSUK Frontend on a project which has a non-standard location for `node_modules`, and as a result, we were getting the following error:
```
sass.CompileError: Error: File to import not found or unreadable: ./node_modules/sass-mq/mq.
on line 17:1 of assets/_dev/node_modules/nhsuk-frontend/packages/core/tools/_sass-mq.scss
from line 9:1 of assets/_dev/node_modules/nhsuk-frontend/packages/core/tools/_all.scss
from line 6:1 of assets/_dev/scss/screen.scss
>> @import './node_modules/sass-mq/mq'; // [1] //
```
After a bit of Googling, I found that govuk-frontend had a similar problem and solved this by [vendoring in SassMQ](https://github.com/alphagov/govuk-frontend/pull/657). I've attempted to replicate this approach in NHS Frontend too.
Thoughts welcome!
> Vendor in Sass-MQ

- .github/workflows/release.yml
- CHANGELOG.md
- package-lock.json
- package.json
Fix for ([Issue 691](https://github.com/nhsuk/nhsuk-frontend/issues/691))
Update Release GitHub Action to use Node environment and set NPM registry
Ensure publishConfig is set to `public` in `package.json`
Tested on a fork with different package name and version so I could publish to my own NPM.
Diff of the fork here: https://github.com/nhsuk/nhsuk-frontend/compare/master...tomdoughty:master
Github action succeeding here: https://github.com/tomdoughty/nhsuk-frontend/runs/1762708040?check_suite_focus=true
> Update release action to fix npm publish

- CHANGELOG.md
- docs/installation/installing-with-npm.md
- packages/components/card/card.js
The JS for the card component current references the old `panel` name. Updating JS to now use `card`
> Updating card JS to use card rather than panel

- CHANGELOG.md
- packages/components/care-card/_care-card.scss
Give the Action link icon sufficient contrast when used in the Care card immediate variant
fixes #588
> Action link icon contrast in the immediate Care card

- CHANGELOG.md
- packages/components/header/_header.scss
accommodate longer service names on the service header by applying a max width
[refs #708]
> accommodate longer service names on the service header

- CHANGELOG.md
- packages/components/breadcrumb/_breadcrumb.scss
- packages/components/details/_details.scss
Resolving https://github.com/nhsuk/nhsuk-frontend/issues/676 - this updates the expander and breadcrumb components to prevent aXe from seeing accessibility violations due to the use of background images on elements that contain text. This fixes the `elements must have sufficient color contrast` warning.
They look pixel-perfect identical across all resolutions.
> [refs #676] Move icons using background into ::before to simplify automated testing

- gulpfile.js
- package-lock.json
- package.json
- packages/core/tools/_typography.scss
Fixes #730
The node-sass module is now deprecated (see https://sass-lang.com/blog/libsass-is-deprecated).
Dart-sass is the way forward - via the sass package on npm (https://www.npmjs.com/package/sass). This change is to migrate to dart-sass.
I've had a look around and can't see any issues.
Don't think we need a changelog entry for this? It doesn't affect anyone consuming the package.
> Switch to dart-sass instead of node-sass

- CHANGELOG.md
- packages/core/README.md
- packages/core/elements/_page.scss
- packages/core/generic/_font-face.scss
- packages/core/settings/_globals.scss
Related: https://github.com/nhsuk/nhsuk-frontend/issues/728
This PR fixes the above issue by separating font loading into a separate stylesheet; disabling the font by default. If a dependent wishes to load fonts from `assets.nhs.uk` they will need to include the new `nhsuk-fonts.css` stylesheet. I've incremented the MAJOR version in `package.json` to signify this as a breaking change for those who are using `nhsuk-frontend` already.
Further reading: https://developers.google.com/web/updates/2020/10/http-cache-partitioning
> Conditionally load fonts to avoid performance issues

- README.md
Over the years this library has grown and has been contributed to by a number of people (both through code and non code contributions), these specific people helped us start the library, but since there have been many more who have helped build and grow it further. So it would be unfair to highlight only a select few. 
Credit to the Government Digital Service remains in code and specific documentation.
> update README to remove specific contributors

- CHANGELOG.md
- packages/components/details/details.js
In order to fix #754, I have stopped polyfilling the details component in browsers that have native support since this is no longer necessary and as evidenced by #754 is actually making the situation worse for screen readers. Removing the polyfil causes Firefox to behave correctly now
- JAWS 2021 Firefox ✔️
- JAWS 2021 Edge ✔️
- JAWS 2021 Chrome ✔️
- JAWS 2021 IE11 ✔️
- NVDA 2021.2 Firefox ✔️
- NVDA 2021.2 Edge ✔️
- NVDA 2021.2 Chrome ✔️
- NVDA 2021.2 IE11 ✔️
- Android 10 Talkback ✔️
- Dragon Naturally Speaking 15 Firefox ❌ Does not work - but as per https://github.com/nhsuk/nhsuk-frontend/pull/773#issuecomment-920884804 - Dragon does not support Firefox
- Dragon Naturally Speaking 15 Edge ✔️
- Dragon Naturally Speaking 15 Chrome ✔️
- Dragon Naturally Speaking 15 IE11 ✔️
> Fix details element in firefox nvda

- CHANGELOG.md
- package-lock.json
- packages/assets/icons/icon-minus.svg
- packages/assets/icons/icon-plus.svg
As spotted by @Tosin-Balogun - the plus and minus SVGs were not rendering correctly when previewed in GitHub.
Removing the duplicated width attribute fixes this.
You'll still find that the GitHub diff still won't render this PR because the _old_ ones were invalid! (Look at the code diff instead of the rich diff to see the change). But if you look here you can see the new ones rendering ok:
https://github.com/nhsuk/nhsuk-frontend/blob/ec6f60291c7e538a32ef0f2239a06a0341d77241/packages/assets/icons/icon-minus.svg
https://github.com/nhsuk/nhsuk-frontend/blob/ec6f60291c7e538a32ef0f2239a06a0341d77241/packages/assets/icons/icon-plus.svg
> Fixing invalid plus/minus svg icons

- CHANGELOG.md
- packages/components/do-dont-list/template.njk
- packages/components/error-summary/template.njk
A recent accessibility audit found that when using VoiceOver on a do/don't list, that the list was not announced as a list. Further investgation found that this was a 'feature' of Safari and VoiceOver and that Apple regarded styling a list with `list-style-type: none` as an indication that the list is no longer a list as you are removing the default visible indication for a list. In our instance, we are restyling the list, so we might still expect it to be announced correctly, as it is with JAWS and NVDA. There is a good explanation of this here: https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html
This issue has also been raised on govuk-frontend - [https://github.com/alphagov/govuk-frontend/issues/1471](https://github.com/alphagov/govuk-frontend/issues/1471).
The suggested …
> Add role=list to lists to fix VoiceOver not announcing as lists

- app/components/input/error-and-prefix-and-suffix.njk
- app/components/input/prefix-and-suffix.njk
- app/components/input/prefix.njk
- app/components/input/suffix.njk
- app/pages/examples.njk
- packages/components/input/_input.scss
- packages/components/input/template.njk
It would be good to have the ability to add prefixes / suffixes to the text input component, similar to the GOV.UK Design System (https://design-system.service.gov.uk/components/text-input#prefixes-and-suffixes).
There is a very common need for users to be able to enter information in things like pounds (£) or weight (kg) - or even to show the frequency of how often something happens e.g per week, month, year etc.
This ticket has been provisionally planned for the September Service Manual/Frontend releases.
Link to issues: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/21 and https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/470
> Add suffix and prefix examples to text input component

- CHANGELOG.md
- packages/components/card/card.scss
This bug is causing the chevron to be misaligned vertically
> Fix invalid scss

- CHANGELOG.md
- package-lock.json
- package.json
- tests/integration/jsdom/header.test.js
> Unit tests for header.js

- CHANGELOG.md
- packages/components/button/button.js
- packages/components/character-count/character-count.js
- packages/components/checkboxes/checkboxes.js
- packages/components/details/details.js
- packages/components/error-summary/error-summary.js
- packages/components/radios/radios.js
- packages/components/tabs/tabs.js
- packages/nhsuk.js
- Add and export new `initAll` method in `nhsuk.js`, and pass document by default, but allowing smaller DOM scopes to be passed. This allows new nhsuk-frontend JS components to be initialised after page load, such as in new pieces of DOM added by JavaScript.
- This fixes [issue 906](https://github.com/nhsuk/nhsuk-frontend/issues/906) where button elements added _after_ the page has loaded would not benefit from the button component's JS behaviours (double click prevention and space bar activation for links).
Fixes https://github.com/nhsuk/nhsuk-frontend/issues/906
> Fixed bug where buttons added after page load don't activate JS behaviours

- .github/workflows/pull-request.yml
- sonar-project.properties
Add sonarcloud to pull request pipeline
> Add sonarcloud to pull request pipeline

- packages/components/header/_header.scss
Fixes an issue raised in a recent accessibility audit.
Dig report: https://alpha.hugr.app/view/7e2117#DIG602
Dig reported that the search bar placeholder text is low contrast.
> fix low contrast of placeholder text in firefox

- CHANGELOG.md
- app/components/inset-text/index.njk
- packages/components/inset-text/README.md
- packages/components/inset-text/template.njk
Fixes #950. I think we expect all Nunjucks arguments to be lowercase - but here is is uppercase.
I think it would be a breaking change to swap it over, so I've added support for `params.html` in preference whilst still accepting `params.HTML`. It could potentially be considered cleaning up for a future major version release.
> Fix inset-text not supporting html param

- app/pages/examples.njk
- app/styles/lists.njk
- packages/core/styles/_lists.scss
Adds additional spacing at the beginning of nested lists, and removes unnecessary spacing at the end of them.
Resolves #430
An alternative to #920 using margin-top instead inserting a pseudo-element with bottom margin.
> Adjust nested list spacing

- CHANGELOG.md
- app/components/all.njk
- app/components/breadcrumb/index.njk
- app/components/button/link.njk
- app/components/contents-list/index.njk
- packages/components/breadcrumb/README.md
- packages/components/contents-list/README.md
This avoids broken links.
Fixes #956
> Change example links to a hash

- CHANGELOG.md
- packages/core/settings/_globals.scss
Updates `$nhsuk-page-width` to be a SASS default, which would let teams override it. Nearly every other item in `globals.scss` can be overridden already. This works the same way as GOV.UK for setting page width.
> Let page width be overridden

- docs/contributing/coding-standards.md
The inset text component was updated to support a lowercase `html` param in https://github.com/nhsuk/nhsuk-frontend/pull/951
Thanks @paulrobertlloyd for spotting. 👀
> Use lowercase html param in Inset text example

- CHANGELOG.md
- packages/components/date-input/template.njk
Remove pattern attribute from date input component
This matches the update govuk-frontend has done
> Removing pattern from date input to follow govuk-frontend

- CHANGELOG.md
- packages/components/select/_select.scss
This fixes a minor bug with the select component in Safari, which is that the `min-height` property is ignored when the default native appearance is used, resulting in a select which is only 30px high. (Other browsers such as Chrome and Firefox seem to apply the minimum height.)
This restores the select to its previous fixed height of 40px. As the select will never wrap onto 2 or more lines (instead the text gets truncated), having a fixed height should be fine.
Additionally, this also introduces a minimum width to the select component (this property does work in all browsers), in case the options in the select are very short. In these cases, having a wider select means for a bigger target area, and is closer to what users expect. I’ve followed the GOV.UK Design System in setting the …
> Update height and set minimum width of Selects

- CHANGELOG.md
- package-lock.json
- package.json
> update changelog for release

- CHANGELOG.md
- packages/core/settings/_colours.scss
SASS is showing the following deprecation warning. Example:
```
Deprecation Warning: $weight: Passing a number without unit % (50%*%) is deprecated.
To preserve current behavior: calc($weight / 1% / 1% * 1%)
More info: https://sass-lang.com/d/function-units
╷
72 │   @return mix(black, $color, $percentage * 1%);
│           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
packages/core/settings/_colours.scss 72:11  shade()
packages/core/settings/_colours.scss 90:29  @import
packages/core/settings/_all.scss 6:9        @import
packages/core/all.scss 6:9                  @import
packages/nhsuk.scss 2:9                     root stylesheet
```
As we are always passing a percentage to the `tint` and `shade` functions, we don’t need to multiple the incoming value by 1%. This resolves this warning.
> Fix Sass deprecation on `mix` function (passing a number without unit)

- CHANGELOG.md
- packages/components/fieldset/_fieldset.scss
- packages/components/label/_label.scss
- packages/core/settings/_typography.scss
- packages/core/styles/_typography.scss
- packages/core/tools/_typography.scss
In our typography scale, the large size seems smaller than necessary. On GOV.UK it's 36px, whereas in NHS it's 32px. Once our heading guidance is updated, we may see more headings using the large size, so I am proposing updating our type scale to use 36px rather than 32px.
The GOV.UK scale goes:
- Desktop: 24px > 36px > 48px
- Mobile: 21px > 27px > 32px
NHS:
- Desktop: 24px > 32px > 48px
- Mobile: 20px > 24px > 32px
To swap the size would likely be a breaking change - users may be relying on the `.nhsuk-u-font-size-32` classes or passing 32 to the font mixins.
I am proposing adding 36 to the scale and updating the heading mixins to use it, and leave 32 for now. We can then remove 32 from the scale at the next major version.
| Mobile before | Mobile after |
|----------|----------| …
> Add 36 to type scale and swap headings to use it

- CHANGELOG.md
Type scale work introduced a breaking change, replacing the font size class `nhsuk-u-font-size-32` with `nhsuk-u-font-size-36`.
> Update changelog - add breaking change info for font size modifier class

- packages/components/tables/_tables.scss
- packages/core/tools/_mixins.scss
This fixes a bug in the nhsuk-u-visually-hidden helper class where any whitespace surrounding visually hidden text isn't announced by screen readers.
This fix was added to `govuk-frontend` in [pull request #3868](https://github.com/alphagov/govuk-frontend/pull/3836) and released in [v4.7.0](https://github.com/alphagov/govuk-frontend/releases/tag/v4.7.0) and has been re-applied here.
Thanks to @hannalaakso for the work upstream. 🙌 
I’ve also followed the approach of the GOV.UK Design System team of adding a Typography page with examples of using visually-hidden text, to make testing easier.
> Announce whitespace in screen reader announcements of visually hidden text

- package-lock.json
- package.json
`package.json` lists Prettier as `^3.3.2`. This means that different versions can be installed locally as that ran during CI, which always installs the latest version (currently v3.3.3).
This is [recommended by Prettier](https://prettier.io/docs/en/install#summary):
> Install an exact version of Prettier locally in your project. This makes sure that everyone in the project gets the exact same version of Prettier. Even a patch release of Prettier can result in slightly different formatting, so you wouldn’t want different team members using different versions and formatting each other’s changes back and forth.
This has caused issues recently, with a patch release changing how `box-shadow` rules get formatted.
> Pin Prettier version

- .github/workflows/pull-request.yml
> [`npm ci`](https://docs.npmjs.com/cli/v10/commands/npm-ci) is similar to [npm install](https://docs.npmjs.com/cli/v10/commands/npm-install), except it's meant to be used in automated environments such as test platforms, continuous integration, and deployment -- or any situation where you want to make sure you're doing a clean install of your dependencies.
> Use npm ci to install dependencies for testing

- CHANGELOG.md
- app/_templates/page.njk
- app/components/all.njk
- app/components/header/header-logo.njk
- app/components/header/header-navigation.njk
- app/components/header/header-org-white-nav.njk
- app/components/header/header-org-white.njk
- app/components/header/header-org.njk
- app/components/header/header-search.njk
- app/components/header/header-service-name-with-nav.njk
- app/components/header/header-service-name.njk
- app/components/header/header-transactional-service-name.njk
- app/components/header/index.njk
- packages/components/header/README.md
- packages/components/header/template.njk
Prior to any work on adding account links to the header, or refining its design, this PR aims to reduce the complexity of the component template, and remove repetition of navigation and search markup.
This PR:
- Shows or hides navigation and search markup by querying the presence of values for `params.primaryLinks` and `params.search` respectively
- Removes repetition of navigation and search markup thanks to simplified logic and fewer variables
- Uses the [`default` filter](https://mozilla.github.io/nunjucks/templating.html#default-value-default-boolean) for values as opposed to longer `if`/`else` tags
- Adds an option to set the (visually hidden) label for the search input
- Allows a transactional service name to be used alongside navigation and/or search
- Changes the default search …
> Simplify template logic for header component

- CHANGELOG.md
- packages/components/header/_header.scss
- packages/components/header/header.js
- tests/integration/jsdom/header.test.js
Fixes issue where navigation list with too many items would not show the ‘Menu’ toggle on desktop, and items would overflow.
Also updates navigation on desktop breakpoint to match that used at smaller breakpoints (the navigation items ranged left):
> Fix header navigation overflow on desktop

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
`actions/checkout@v2` is deprecated and now shows a warning on action annotations.
> Update GitHub Actions checkout dependency

- CHANGELOG.md
- app/components/details/index.njk
- packages/components/details/README.md
- packages/components/details/template.njk
> Support lowercase html arg

- app/components/header/header-account-custom-html.njk
- app/components/header/header-account-logged-in.njk
- app/components/header/header-account-rbac.njk
- app/components/header/header-org-white-account.njk
- app/components/header/header-service-name-with-account-search-nav.njk
- packages/components/header/_header.scss
- packages/components/header/template.njk
Some items in the header account area, but most likely any ‘Log out’ button, will require form submission rather than linking to a page.
This PR adds support for having button items (in addition to having a link or only text), and adds the following 2 options:
`[]item.action` – The form action, for example `"/log-out"`
`[]item.method` – The form method, optional and defaults to `"post"`
If you provide `item.action`, a button will be used instead. Using `item.href` will override any `item.action` parameter.
These options currently presume the presence of a surrounding `<form>`; perhaps we should add a `<form>` element if you use one or more `item.action` parameters?
The button is styled to look and behave like a link:
<p><img width="408" alt="Screenshot of header navigation with ‘Log out’ …
> Support form submission from header account items

- CHANGELOG.md
- packages/core/objects/_main-wrapper.scss
Added bottom padding to the `nhsuk-main-wrapper--l` modifier class.
It was using the bottom padding from the `nhsuk-main-wrapper` class, which is too small.
| Before | After |
| -------|-------|
| <img width="421" alt="Screenshot 2025-03-28 at 13 31 01" src="https://github.com/user-attachments/assets/bcf64f2f-0644-4388-a5d2-5a0ac68e2966" /> | <img width="428" alt="Screenshot 2025-03-28 at 13 30 32" src="https://github.com/user-attachments/assets/895d58dc-c8c7-4075-b27c-d6c46f6ee017" /> |
> Add bottom padding to `nhsuk-main-wrapper--l` 

- CHANGELOG.md
Causes error if copy and pasted (as I just did!).
> Fix Nunjucks code snippet typo

- CHANGELOG.md
- packages/components/input/_input.scss
Added fix to stop text input focus style being overlapped by the suffix.
| Before | After |
| -------|-------|
| <img width="266" alt="Screenshot 2025-04-24 at 10 28 23" src="https://github.com/user-attachments/assets/cf8a78b4-2d8f-403e-92c6-bcf5bc9745fb" /> | <img width="272" alt="Screenshot 2025-04-24 at 10 28 40" src="https://github.com/user-attachments/assets/215176dc-ff6d-4bdf-84d4-0555fadadf4f" /> |
Also added fix for input width (with prefix/suffix) on small screens.
| Before | After |
| -------|-------|
|  <img width="306" alt="Screenshot 2025-04-24 at 11 28 00" src="https://github.com/user-attachments/assets/1e819bc1-56fb-4e3f-9405-890633f201ce" /> |  <img width="308" alt="Screenshot 2025-04-24 at 11 27 29" src="https://github.com/user-attachments/assets/70aa289b-f10b-41a9-9336-a1 …
> Fix text input with prefix/suffix focus and width 

- app/components/all-links.njk
- app/index.njk
Following #1283 which added a page showing all the button variants on different background colours, this adds a page showing all the link variants on different background colours.
A blue background variant (with white link text) will be added in #1269.
In future we’ll ideally add examples showing visited, hover and active link styles - but that will need extra CSS to fake the pseudo-classes, like this: https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend-review/postcss.config.mjs#L16-L21
> Add all links example page

- CHANGELOG.md
- app/components/hero/hero-with-html.njk
- packages/components/button/_index.scss
- packages/components/hero/_index.scss
The reverse button in the Hero component was being styled as white-on-white when the button was using a link tag instead of a button tag:
This was due to a conflict with the default link style in the Hero component.
This fixes that by only applying the default link style to links which do not contain the `.nhsuk-button` class.
> Fix for reverse button in hero

- CHANGELOG.md
- packages/template.njk
This shouldn’t be included by default. Services using the template can set meta descriptions (and any other meta tags) using the `head` block.
> Remove empty meta description tag

- CHANGELOG.md
- packages/core/settings/_typography.scss
This removes the 24 point from the typography scale, after having previously deprecated it in #1294.
- 24px is not listed as font size in the [typography scale](https://service-manual.nhs.uk/design-system/styles/typography)
- The difference between 24px and 26px is slight, and having 3 sizes in the 22px - 26px range, reduces the contrast between heading sizes (which is why the medium heading size was increased from 24px to 26px last year).
- The 24px font size was only used for a few components, and these have now been updated:
- Panel headings (feature card, panel table, warning callout, do and don’t lists)
- Pagination
- Panel
- Lede text (`.nhsuk-lede-text`)
- Large text (`.nhsuk-body-l`)
- Using 24px for panel headings means these don’t align with other headings on a page
> Remove 24px from typography scale

- packages/nhsuk-frontend-review/src/_templates/layout.njk
Add `noindex` to `layout.njk` to prevent review app pages from being shown in search engine results.
> Add noindex to prevent review app from showing in search engines

- packages/nhsuk-frontend/src/nhsuk/components/header/_index.scss
The description of the responsive behaviour of the header component no longer matches how the header actually behaves. We could either remove it, or use this area to outline the different colour variants and how the overflow menu works.
> Update component description for header component

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/radios/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/summary-list/macro-options.mjs
This PR fixes some macro options that should be represented as nested objects:
```console
'actions.classes'
'actions.items'
'conditional.html'
'key.html'
'key.text'
'value.classes'
'value.html'
'value.text'
```
It improves the **Nunjucks macro options** documentation for checkboxes, radios and summary list
> Fix component nested Nunjucks macro options

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/components/character-count/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/character-count/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/input/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/input/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/select/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/select/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/textarea/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/textarea/template.njk
This PR adds the following Nunjucks line to a few missed components:
```njk
{%- set id = params.id if params.id else params.name -%}
```
Notably the [**Select** component](https://service-manual.nhs.uk/design-system/components/select) where it was only partially used
See this issue https://github.com/alphagov/govuk-frontend/issues/3497 for more information
> Update components to set a default `id` based on `name`

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/components/character-count/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/date-input/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/input/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/radios/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/select/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/select/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/textarea/template.njk
This PR adds a feature from GOV.UK Frontend to close https://github.com/nhsuk/nhsuk-frontend/issues/1348
* https://github.com/alphagov/govuk-frontend/pull/1347
The following components were documented to support `params.fieldset.describedBy` but it was missing:
* Checkboxes
* Radios
* Date input
The following components were documented to support `params.describedBy` but it was missing:
* ~Character count~
* Textarea
* Text input
**Note:** Character count should not support `params.describedBy` as it must be set to the "count message" hint ID instead
> Support initial `aria-describedby` on all form fields

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/components/character-count/character-count.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/character-count/character-count.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/checkboxes.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/checkboxes.mjs
- packages/nhsuk-frontend/src/nhsuk/components/header/header.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/header/header.mjs
- packages/nhsuk-frontend/src/nhsuk/components/radios/radios.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/radios/radios.mjs
- packages/nhsuk-frontend/src/nhsuk/components/skip-link/skip-link.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/skip-link/skip-link.mjs
- packages/nhsuk-frontend/src/nhsuk/components/tabs/tabs.mjs
This PR follows https://github.com/nhsuk/nhsuk-frontend/pull/1459 and throws `ElementError` for all missing elements
We're following GOV.UK Frontend's lead with this, especially for services that don't use the Nunjucks components
> Throw `ElementError` for all missing elements

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/common.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/common.mjs
- packages/nhsuk-frontend/src/nhsuk/components/button/button.mjs
- packages/nhsuk-frontend/src/nhsuk/components/character-count/character-count.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/checkboxes.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/checkboxes.mjs
- packages/nhsuk-frontend/src/nhsuk/components/error-summary/error-summary.mjs
- packages/nhsuk-frontend/src/nhsuk/components/hero/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/radios/radios.mjs
- packages/nhsuk-frontend/src/nhsuk/components/skip-link/skip-link.mjs
- packages/nhsuk-frontend/src/nhsuk/components/tabs/tabs.mjs
Following https://github.com/nhsuk/nhsuk-frontend/issues/1236, this PR removes various features no longer needed, for example:
* Add common helper `getFragmentFromUrl()` to replace `SkipLink.getHref()` IE workaround
* Skip unnecessary [`pageshow` feature](https://caniuse.com/mdn-api_window_pageshow_event) detection for IE8–10
* Remove [deprecated `event.keyCode`](https://caniuse.com/mdn-api_keyboardevent_keycode)
* Remove tab component unused custom events
> Remove deprecated code and legacy feature detection

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/components/button/_index.scss
To resolve #1372
There may be a smarter way, to not apply focus styles on active buttons, but I couldn't get that working and this seems to work.
> Fix styles for button as link :visited when :active and :focus

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/components/character-count/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/date-input/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/date-input/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/input/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/input/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/radios/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/radios/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/select/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/textarea/macro-options.mjs
- packages/nhsuk-frontend/src/nhsuk/components/textarea/template.njk
Previous updates to NHS.UK frontend have added `attributes` support to some component form groups
This PR reviews all components and adds support where it was missed
The following components support `params.formGroup.attributes` but it's not documented:
* Character count
* Select
The following components do not support `params.formGroup.attributes`:
* Checkboxes
* Radios
* Date input
* Text input
* Textarea
> Fix missing `attributes` option on form groups

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/common/index.mjs
- packages/nhsuk-frontend/src/nhsuk/component.mjs
- packages/nhsuk-frontend/src/nhsuk/components/button/button.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/button/button.mjs
- packages/nhsuk-frontend/src/nhsuk/components/character-count/character-count.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/character-count/character-count.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/checkboxes.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/checkboxes.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/error-summary/error-summary.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/error-summary/error-summary.mjs
- packages/nhsuk-frontend/src/nhsuk/components/error-summary/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/header/header.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/header/header.mjs
- packages/nhsuk-frontend/src/nhsuk/components/header/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/radios/radios.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/radios/radios.mjs
- packages/nhsuk-frontend/src/nhsuk/components/radios/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/skip-link/skip-link.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/skip-link/skip-link.mjs
- packages/nhsuk-frontend/src/nhsuk/components/skip-link/template.njk
- packages/nhsuk-frontend/src/nhsuk/components/tabs/tabs.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/tabs/tabs.mjs
- packages/nhsuk-frontend/src/nhsuk/errors/index.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/errors/index.mjs
This PR fixes components that lack `data-module` attributes:
```patch
- <div class="nhsuk-checkboxes">
+ <div class="nhsuk-checkboxes" data-module="nhsuk-checkboxes">
```
```patch
- <div class="nhsuk-radios">
+ <div class="nhsuk-radios" data-module="nhsuk-radios">
```
```patch
- <div class="nhsuk-error-summary">
+ <div class="nhsuk-error-summary" data-module="nhsuk-error-summary">
```
```patch
- <header class="nhsuk-header">
+ <header class="nhsuk-header" data-module="nhsuk-header">
```
```patch
- <a class="nhsuk-skip-link">
+ <a class="nhsuk-skip-link" data-module="nhsuk-skip-link">
```
> Add missing `data-module` attributes to components

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/common/index.mjs
- packages/nhsuk-frontend/src/nhsuk/component.mjs
- packages/nhsuk-frontend/src/nhsuk/components/button/button.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/character-count/character-count.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/checkboxes/checkboxes.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/error-summary/error-summary.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/header/header.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/radios/radios.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/skip-link/skip-link.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/components/tabs/tabs.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/errors/index.jsdom.test.mjs
- packages/nhsuk-frontend/src/nhsuk/errors/index.mjs
This PR copies GOV.UK Frontend in https://github.com/alphagov/govuk-frontend/pull/5272
We now prevent JavaScript from initialising components multiple times (e.g. accidental React rerenders)
```js
import { Button } from 'nhsuk-frontend'
const $root = document.querySelector('.app-button')
new Button($root) // ✅
new Button($root) // 🔥
```
> Prevent multiple initialisations of a single component instance

- packages/nhsuk-frontend-review/tasks/assets.mjs
- packages/nhsuk-frontend-review/tasks/html.mjs
- shared/tasks/files.mjs
- shared/tasks/scripts.mjs
- shared/tasks/styles.mjs
This PR updates older Gulp tasks to use the `files.write()` helper as part of https://github.com/nhsuk/nhsuk-frontend/issues/1237
I've also updated tasks to show a clear `inputPath` versus `outputPath` before calling `files.write()`
> Update tasks to use `files.write()` helper

- CHANGELOG.md
- packages/nhsuk-frontend/package.json
- packages/nhsuk-frontend/tsconfig.json
- shared/tasks/scripts.mjs
- shared/tasks/styles.mjs
This PR adds type declaration support for JavaScript code autocomplete (and type checking)
It helps massively when integrating our [`nhsuk-frontend` npm package](https://www.npmjs.com/package/nhsuk-frontend) with projects using TypeScript and React
<br>
<br>
Closes https://github.com/nhsuk/nhsuk-frontend/issues/1464
> Export type declarations ` *.d.mts` for NHS.UK frontend

- CHANGELOG.md
- package-lock.json
- packages/nhsuk-frontend/package.json
Bumps the version number to v10.0.0-internal.1 ready to install either:
```console
npm install nhsuk-frontend@10.0.0-internal.1
npm install nhsuk-frontend@next
```
The version bump was generated using:
```console
npm version prerelease --no-git-tag-version --preid internal --workspace nhsuk-frontend
```
> Update package version to v10.0.0-internal.1

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/core/_index.scss
- packages/nhsuk-frontend/src/nhsuk/core/_nhsuk-frontend-properties.scss
- packages/nhsuk-frontend/src/nhsuk/core/all.scss
- packages/nhsuk-frontend/src/nhsuk/core/core.unit.test.mjs
- packages/nhsuk-frontend/src/nhsuk/core/settings/_all.scss
- packages/nhsuk-frontend/src/nhsuk/core/tools/_all.scss
- packages/nhsuk-frontend/src/nhsuk/core/tools/_shape-arrow.scss
- packages/nhsuk-frontend/src/nhsuk/core/vendor/sass-mq.scss
This PR fixes an issue raised by @paulrobertlloyd following the [`nhsuk-frontend@10.0.0-internal.1` pre-release](https://github.com/nhsuk/nhsuk-frontend/releases/tag/v10.0.0-internal.1)
We now load Sass `"settings"` first before nested `"settings/breakpoints"` etc to fix:
```console
Error: This module was already loaded, so it can't be configured using "with".
┌──> ../../../../packages/nhsuk-frontend/src/nhsuk/core/_index.scss
6 │   @forward "settings";
│   ^^^^^^^^^^^^^^^^^^^ new load
╵
┌──> ../../../../packages/nhsuk-frontend/src/nhsuk/core/tools/_functions.scss
2 │   @use "../settings" as *;
│   ━━━━━━━━━━━━━━━━━━━━━━━ original load
╵
╷
2 │ ┌         @forward "core" with (
3 │ │           $nhsuk-page-width: 1100px
4 │ │         );
│ └─────────^ configuration
╵
_index.scss 6:1  @forward …
```
> Fix Sass "Error: This module was already loaded"

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/assets/icons/icon-close.svg
- packages/nhsuk-frontend/src/nhsuk/core/styles/_icons.scss
Partially addresses #1028. The close icon is no longer used by the mobile menu in the header (the chevon rotates).
This PR will require a respective change to the service manual to remove this from the [table of icons](https://service-manual.nhs.uk/design-system/styles/icons).
> Remove unused close icon

- CHANGELOG.md
- docs/installation/installing-compiled.md
- packages/nhsuk-frontend/src/nhsuk/components/skip-link/_index.scss
- packages/nhsuk-frontend/src/nhsuk/core/objects/_width-container.scss
- packages/nhsuk-frontend/src/nhsuk/core/objects/width-container.unit.test.mjs
- packages/nhsuk-frontend/src/nhsuk/template.njk
@colinrotherham noticed this, and nerd-snipped me into contributing a new feature for it.
**NHS.UK frontend** doesn't support the dreaded "notch" (or Display Cutouts as they're known) on various devices. See the unused white area on the left hand side here:
The `safe-area-inset-*` variables were [added in iOS 11](https://webkit.org/blog/7929/designing-websites-for-iphone-x/), and Android P added support via Chrome for Android 69: https://www.chromestatus.com/feature/5710044637167616
Firefox added support in v65:
https://bugzilla.mozilla.org/show_bug.cgi?id=1462233
This pull request adds the initial support to patch `.nhsuk-width-container`
See (and in tribute to) https://github.com/alphagov/govuk-frontend/pull/1176
The implementation used by GOV.UK Frontend has been adapted slightly for …
> Accommodate camera notches

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/core/settings/_globals.scss
Absolute rabbit hole this one, but spotted that `$nhsuk-header-spacing` needs removing, and so did a search across the other global variables.
Notes:
- `$nhsuk-font-light` wasn’t removed to prevent needing to release a breaking change… in 2019 (see: https://github.com/nhsuk/nhsuk-frontend/pull/460#issuecomment-502674057)
- `$nhsuk-font-family-print` isn’t used anywhere… but probably should (in GOV.UK Frontend it is used in the `govuk-typography-common` mixin)
- the following ‘global’ variables should probably be moved to their respective components, but have left them here for now:
- `$nhsuk-border-width-inset-text`
- `$nhsuk-hero-border`
- `$nhsuk-border-table-header-width`
- `$nhsuk-border-table-cell-width`
> Remove unused global Sass variables

- packages/nhsuk-frontend-review/src/examples/all-tags.njk
This PR updates the [**All tag examples** page](https://nhsuk-frontend-pr-1538.herokuapp.com/nhsuk-frontend/examples/all-tags/) to use a responsive table
We made a similar change to the [**All icon examples** page](https://nhsuk-frontend-pr-1538.herokuapp.com/nhsuk-frontend/examples/all-icons/) in https://github.com/nhsuk/nhsuk-frontend/pull/1521
> Update all tags preview page to use responsive table

- CHANGELOG.md
- package-lock.json
- packages/nhsuk-frontend/package.json
Bumps the version number to v10.0.0-internal.3 ready to install either:
```console
npm install nhsuk-frontend@10.0.0-internal.3
npm install nhsuk-frontend@next
```
The version bump was generated using:
```console
npm version prerelease --no-git-tag-version --preid internal --workspace nhsuk-frontend
```
> Update package version to v10.0.0-internal.3

- .github/workflows/release.yml
This PR prevents the next v9.x support release from bumping v10.x off the `latest` npm tag
Follows the naming convention from GOV.UK Frontend:
```console
npm install nhsuk-frontend@latest
npm install nhsuk-frontend@10.0.0
```
```console
npm install nhsuk-frontend@latest-v9
npm install nhsuk-frontend@9.6.4
```
> Tag v9 releases as `latest-v9` not `latest`

- packages/nhsuk-frontend/src/nhsuk/macros/attributes.unit.test.mjs
- shared/lib/nunjucks/index.mjs
This PR adds test coverage for the `nhsukAttributes` macro, copied from GOV.UK Frontend
> Add tests for `nhsukAttributes` macro

- CHANGELOG.md
- packages/nhsuk-frontend/src/nhsuk/components/card/_index.scss
- packages/nhsuk-frontend/src/nhsuk/components/card/macro-options.mjs
- shared/lib/components.mjs
Remove underline from action link when used in emergency care card. 
Currently, because of the default link styling adding `text-decoration: underline`, there is no hover state.
Before:
After:
> Fix styling of action link when used in emergency cards
