CHANGELOG.md
app/views/macros/review-date.njk
app/views/pages/components/index.njk
src/components/review-date/README.md
src/components/review-date/macro.njk
src/components/review-date/template.njk

Review component template, macro and documentation.

:date: review date component template, macro and documentation

---

app/views/macros/blockquote.njk
app/views/macros/image.njk
app/views/pages/components/index.njk
src/components/images/README.md
src/components/images/macro.njk
src/components/images/template.njk

image component template, macro and documentation

image component template, macro and documentation

---

CHANGELOG.md
app/views/pages/components/index.njk
src/components/tables/README.md
src/components/tables/macro.njk
src/components/tables/template.njk

Table component template, macro and documentation. Also reorganise the macro imports on the example pages to alphabetical order.

Table component

---

.travis.yml

Use latest version of node in travis configuration

:robot: travis ci configuration

---

.editorconfig

What is EditorConfig?
EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.
https://editorconfig.org/

Add an editorconfig file for consistency

---

app/views/index.njk

:pencil: Spelling fix

---

packages/core/tools/_sass-mq.scss

Fix incorrect sass-mq import from node_modules path

---

.travis.yml
package.json

Fix Travis build on tags and bump package version

---

package-lock.json
package.json
tasks/docs.js

Use gulp-open to open localhost:3000 when serving the docs

Automatically open the browser when serving the docs

---

docs/_templates/page.njk
docs/index.njk
docs/pages/about.njk
docs/pages/examples.njk
docs/pages/install.njk
package-lock.json
packages/core/styles/_typography.scss

Updated and added content to the frontend pages, including installation, examples and about.
Also, fixed a bug for the `nhsuk-body-l` margin-bottom.

[refs #165] Added / updated content on frontend pages

---

docs/index.njk
docs/pages/about.njk
docs/pages/examples.njk
docs/pages/install.njk

Fix broken page URL root path for GitHub pages

---

package.json

Bump package version for release

---

packages/components/footer/_footer.scss

Add child combinator selectors for logo link and visually hidden span

[refs #138] Minor performance improvement to footer logo elements

---

package.json

Bump version for prerelease 0.1.4 🍾 

---

docs/components/warning-callout.njk
packages/components/warning-callout/README.md
packages/components/warning-callout/template.njk

[refs #156] Add Nunjucks information for warning callout

---

packages/components/tables/README.md
packages/components/tables/template.njk

[refs #156] Add Nunjucks information for tables

---

packages/components/promo/README.md

[refs #156] Add Nunjucks information for the promo

---

packages/components/pagination/README.md
packages/components/pagination/template.html
packages/components/pagination/template.njk

Add Nunjucks argument tables and reorder attributes in template

[refs #156] Add Nunjucks information for pagination

---

packages/components/nav-a-z/README.md
packages/components/nav-a-z/template.html
packages/components/nav-a-z/template.njk

Add Nunjucks argument tables and reorder attributes in templates

[refs #156] Add Nunjucks information for nav a-z

---

packages/components/pagination/README.md

Replace review date with pagination!

[refs #156] Correct reference to pagination in readme

---

README.md

Add thanks to Phil Sherry in main README

---

package.json

Bump version to 0.1.5 for prerelease

---

package-lock.json
package.json

Update project dependencies for security alerts

---

package.json
packages/components/footer/template.njk
packages/components/header/template.njk

Inline the NHS logo SVG icon to fix importing nunjucks macros in
projects.

[refs #107] Remove NHS logo SVG include

---

packages/components/inset-text/README.md
packages/components/inset-text/template.njk

Add classes and attributes Nunjucks parameters.
Add Nunjucks arguments table to README.

[refs #172] Add Nunjucks parameters

---

docs/components/list-panel.njk
packages/components/list-panel/README.md
packages/components/list-panel/template.html
packages/components/list-panel/template.njk

Put each list panel in an ordered list.

[refs #173] Put each list panel in a list item

---

docs/contributing/README.md

Sentences front-loaded, guidance text brought before the code snippets, email address shown in the link, etc.

Updates to the contributing documentation

---

packages/components/pagination/README.md
packages/components/pagination/_pagination.scss
packages/components/pagination/template.html
packages/components/pagination/template.njk

Add extra visually hidden colon to help with screen readers.
Move pagination into a list.
Add outline to hover and focus states so is visible when in high
contrast mode on Windows.

[refs #174] Update pagination markup and styling

---

packages/core/README.md

[refs #265] Rename colour to color in README

---

README.md
docs/contributing/coding-standards/README.md
docs/contributing/coding-standards/browser-support.md
docs/index.njk

Update documentation after suggestions from Caroline Jarrett and others

[refs #156] Update READMEs

---

CHANGELOG.md
docs/_templates/page.njk
docs/components/footer.njk
packages/components/footer/README.md
packages/components/footer/template.njk

Added the homeHref argument so the NHS logo link can be changed, it defaults to "/". Also make the NHS logo showLogo argument is not required and shows the NHS logo by default. With showLogo false hiding the NHS logo.
Thanks to @jbroodie for finding this issue.

[refs #168] Footer nunjucks macro params and documentation

---

docs/components/footer-no-logo.njk
packages/components/back-link/README.md

Footer and back link example bugs

---

packages/core/README.md

Document the usage of sass-mq for media queries.
https://github.com/sass-mq/sass-mq

[refs #156] Documentation for sass-mq media queries

---

gulpfile.js

Add details.js to gulp file to be compiled into the main javascript

[refs #162] Add details javascript to the compiled javascript

---

package.json

[refs #288] Bump nhsuk-frontend version to 0.5.3

---

CHANGELOG.md
README.md
docs/_templates/layout.njk
docs/_templates/page.njk
docs/components/form-elements.njk
docs/components/select/hint-error.njk
docs/components/select/index.njk
docs/contributing/README.md
docs/contributing/coding-standards/css.md
docs/contributing/coding-standards/nunjucks-api.md
docs/index.njk
docs/installation/installing-compiled.md
docs/installation/installing-with-npm.md
docs/installation/installing-with-pypi.md
docs/installation/installing-with-yarn.md
docs/pages/about.njk
docs/pages/examples.njk
docs/pages/install.njk
docs/pages/transactional-test-pages/index.njk
docs/pages/transactional-test-pages/ndop-1.njk
docs/pages/transactional-test-pages/ndop-2.njk
docs/pages/transactional-test-pages/ndop-3.njk
packages/components/select/README.md

Content changes to documentation

---

packages/components/do-dont-list/README.md

Make link to guidance more prominent

---

docs/components/care-card-immediate.njk
docs/components/care-card-non-urgent.njk
docs/components/care-card-urgent.njk
docs/components/warning-callout.njk
packages/components/care-card/README.md
packages/components/footer/README.md
packages/components/header/README.md
packages/components/inset-text/README.md
packages/components/warning-callout/README.md

@sarawilcox has provided some content improvements to help link the service manual and frontend library more efficiently.

Service manual content improvements 

---

packages/components/header/_header.scss
packages/components/header/autocomplete.js

fixed click action and some spelling :)

---

packages/components/back-link/template.njk
packages/components/breadcrumb/template.njk
packages/components/care-card/template.njk
packages/components/do-dont-list/template.njk
packages/components/emergency-alert/template.njk
packages/components/feedback-banner/template.njk

Reodered html attributes

---

packages/components/back-link/README.md
packages/components/back-link/template.njk
packages/components/breadcrumb/README.md
packages/components/breadcrumb/template.njk
packages/components/care-card/README.md
packages/components/care-card/template.njk
packages/components/do-dont-list/README.md
packages/components/do-dont-list/template.njk
packages/components/emergency-alert/README.md
packages/components/emergency-alert/template.njk
packages/components/feedback-banner/README.md
packages/components/feedback-banner/template.njk
packages/components/header/README.md
packages/components/header/template.njk
packages/components/hint/template.njk
packages/components/images/README.md
packages/components/images/template.njk
packages/components/label/template.njk
packages/components/nav-a-z/template.njk
packages/components/pagination/template.njk
packages/components/radios/README.md
packages/components/radios/template.njk

Edited the order of attributes for components in the front end library. Jira ticket nr-660

Attribute order

---

CONTRIBUTING.md
README.md
app/pages/about.njk

Change Slack channel to the NHS service manual public channel

Change Slack channel to the NHS service manual public channel

---

packages/components/care-card/README.md
packages/components/care-card/template.njk

Fix issue with visually hidden span hiding care card headings

---

package-lock.json
packages/components/care-card/README.md
packages/components/care-card/template.njk

Add the span with role of text to the care card heading

---

app/components/all.njk
app/components/typography.njk

Update macro parameter names on components and typography pages

---

packages/components/details/README.md

[refs #162] Update README dependencies section

---

docs/contributing/backstopJS_tests.md

Use documentation from the official BackstopJS documentation to
explain what BackstopJS is and how the configuration of tests works.

Update BackstopJS documentation

---

README.md

Update README to say release will be in February

---

app/components/panel/index.njk
app/components/panel/panel-grey.njk
app/components/panel/panel-group.njk
app/components/panel/panel-with-label.njk
packages/components/panel/README.md

Changed the content to be more relevant to the NHS

[refs #175] Change panel example content

---

packages/components/checkboxes/README.md

To reflect changes in service manual - as discussed with Caroline J.

Update code and design example

---

packages/components/radios/README.md

Change words in examples to reflect service manual and our style

Change words in examples

---

app/components/checkboxes/hint.njk
app/components/checkboxes/index.njk
app/components/error-summary/index.njk
app/components/radios/divider.njk
app/components/radios/hint.njk
packages/components/checkboxes/README.md
packages/components/error-summary/README.md
packages/components/radios/README.md

Update content to reflect service manual

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
docs/contributing/coding-standards.md
docs/contributing/running-locally.md
package-lock.json
package.json

Create a GitHub template for reporting bugs or issues to the NHS.UK
frontend team view GitHub issues. Also add a link to the code of conduct
within the contributing docs index.

Package.json clean up and contributing documentation

---

CHANGELOG.md
package.json

Update release to 0.9.1

---

.github/PULL_REQUEST_TEMPLATE.md

Add visual tests (BackstopJS) to pull request template checklist

---

CHANGELOG.md
package.json

Update release to 1.0.1

---

CHANGELOG.md
packages/components/feedback-banner/feedback-banner.js
packages/components/header/autocomplete.js
packages/components/header/header.js
packages/components/skip-link/skip-link.js

This is a potential fix for https://github.com/nhsuk/nhsuk-frontend/issues/398
Globally scoped variables were causing issues with JavaScript frameworks such as Angular, so they have been moved to be locally scoped within functions. However, this could be improved as we have to duplicate variables between the multiple functions.
There was also an issue with the autocomplete load event listener with Angular, The wrap-search element was not being found as the page load event listener was coming after the search for the element which caused issues in JavaScript frameworks such as Angular.
Currently testing this out with Angular and ES5/Webpack, also looking for better ways to do this and potentially look for advice on how we write our JavaScript (ES6). …

JavaScript Variable Scope and Hoisting

---

packages/components/back-link/README.md
packages/components/contents-list/README.md
packages/components/details/README.md
packages/components/images/README.md
packages/components/pagination/README.md
packages/components/review-date/README.md
packages/components/skip-link/README.md
packages/components/tables/README.md

Readmes updated:
- back link [refs #202]
- contents list [refs #161]
- details/expander [refs #162]
- images [refs #171]
- pagination [refs #174]
- review date [refs #177]
- skip link [refs #178]
- table [refs #179]

Update component readmes

---

packages/components/feedback-banner/README.md

added some guidance for using the feedback banner component

---

CHANGELOG.md

Update CHANGELOG to increase version to 2

---

CHANGELOG.md
package-lock.json
package.json

Bump version to 2.0.0

---

app/index.njk

Correct heading levels on the 'home page'

---

CHANGELOG.md

populate the release date for version 2.1.0

populate the release date for version 2.1.0

---

CHANGELOG.md
packages/components/header/README.md
packages/components/header/autocomplete.js
packages/components/header/template.njk

Autocomplete fix

---

CHANGELOG.md
packages/components/button/README.md

Button text consistency

---

packages/components/header/README.md

Removed navigation elements from the header with search nunjucks macros

[refs #466] Update header README

---

CHANGELOG.md

update the release date for v2.2.0

---

packages/components/images/README.md

added macro for image without caption
resolves #483

updated nunjuck macro

---

CHANGELOG.md
packages/components/care-card/_care-card.scss

Fix colour contrast issue when using the Details component within the Care card (immediate) ([Issue 475](https://github.com/nhsuk/nhsuk-frontend/issues/475))

colour contrast issue when using the Details component within immediate Care card

---

package-lock.json
package.json

This only affects only development environment for the NHS.UK frontend application, rather than the npm package.

update package dependencies to latest versions

---

CHANGELOG.md

populate the release date for release v2.3.0

populate the release date for release v2.3.0

---

.github/PULL_REQUEST_TEMPLATE.md

update the pull request template to be more relevant

---

CHANGELOG.md
packages/components/footer/README.md
packages/components/footer/template.njk

add copyright override parameter and docs

---

CHANGELOG.md
packages/components/header/_autocomplete.scss
packages/components/header/_header.scss
packages/components/header/autocomplete.js

search drop-down fix

---

CHANGELOG.md
packages/components/header/autocomplete.js

handle the enter keydown event to perform search
Related issue #522

[refs #522] search enter key fix

---

CHANGELOG.md

update the release date for 2.3.1

update the release date for 2.3.1

---

CHANGELOG.md

fix broken GitHub issue link in the change log

fix broken GitHub issue link in the change log

---

packages/components/header/_autocomplete.scss
packages/components/header/_header.scss

fix org header focus styles

---

packages/components/action-link/_action-link.scss
packages/components/back-link/_back-link.scss
packages/components/details/_details.scss
packages/components/header/_autocomplete.scss
packages/components/header/_header.scss
packages/components/promo/_promo.scss

Update active state style for the main nav links. It was conflicting with the new focus styles.
Update hover state style for details and expander component. It now uses the new link hover colour.

Focus styles update

---

packages/components/promo/_promo.scss

Update promo hover and active state style to remove surrounding `box-shadow`.

Update promo hover and active style

---

CHANGELOG.md
package-lock.json
package.json
packages/components/header/_header.scss

- Fix main nav link focus + hover state style
- Bumped version to 3.0.1

Fix main nav link focus + hover state styles

---

package-lock.json
package.json

update dependencies to latest versions

update dependencies to latest versions

---

docs/installation/installing-with-npm.md

fix incorrect component path for node_modules

---

CHANGELOG.md
package-lock.json
package.json

This version includes fix for a bug that prevented users from clicking on options in certain circumstances.
https://github.com/alphagov/accessible-autocomplete/releases/tag/v2.0.2

Use the latest version of the GOV.UK Accessible autocomplete

---

CHANGELOG.md

populate the date for release 3.0.3

---

CHANGELOG.md
packages/components/header/_header.scss

fix colour on the transactional header :focus :hover state

---

CHANGELOG.md
package-lock.json
package.json

:wrench: Update release to v3.0.4

---

package-lock.json
package.json

update devDependencies to latest versions, this doesn't affect the package just the development environment.

update devDependencies to latest versions

---

CHANGELOG.md
docs/installation/installing-compiled.md
docs/installation/installing-with-npm.md

update ES6 JavaScript docs for including conditional JS

---

docs/installation/installing-compiled.md
docs/installation/installing-with-pypi.md
docs/installation/installing-with-yarn.md

fix the formatting of a code snippet in the installing with compiled file docs and also remove some old docs that are no longer used.

fix formatting of code snippet and remove old docs

---

packages/components/warning-callout/README.md

Update preview link in Warning Callout README

---

.travis.yml

unpin BackstopJS version in TravisCI now bug has been fixed

unpin BackstopJS version in TravisCI now bug has been fixed

---

CHANGELOG.md

populate release date for v4.0.0

populate release date for v4.0.0

---

CHANGELOG.md
packages/components/header/_header.scss

Fix for https://github.com/nhsuk/nhsuk-frontend/issues/653

Changed service name link style to include an underline on hover

---

packages/components/card/README.md

fix markdown formatting for title of README

---

packages/components/summary-list/_summary-list.scss

Vertical alignment of Summary-list items proposal.

Vertical alignment of Summary List items fix

---

CHANGELOG.md

CHANGELOG entry for https://github.com/nhsuk/nhsuk-frontend/issues/663

align items to the top in the Summary list component

---

packages/components/warning-callout/README.md

Correct warning callout with custom heading code example in README

---

CHANGELOG.md

Populate release date for 4.1.0

Populate release date for 4.1.0

---

package-lock.json
package.json

populate the correct version number for v4.1.0

---

packages/components/details/README.md

Update the JavaScript file name in the README for the details component.

Update javascript name

---

CHANGELOG.md
packages/components/tables/_tables.scss

Adding display block to IE11 to fix issue with responsive table not wrapping on smaller screens

Issue 712 responsive tables

---

CHANGELOG.md
package-lock.json
packages/components/header/README.md

- populate the release date for v5.0.0
- update the Header markup within the `README` to match the templates
- update dependencies to latest versions

populate the release date for v5.0.0, update header markup and update depens

---

CHANGELOG.md

use the correct release date in the `CHANGELOG`

use the correct release date in the CHANGELOG

---

CHANGELOG.md
docs/installation/installing-with-npm.md
package-lock.json
package.json

Add documentation for including the Error summary JavaScript. Bump to version number to be a new feature.

update docs for Error summary JavaScript and bump version

---

CHANGELOG.md

expand the CHANGELOG entry for the fonts config to include the documentation from the README

expand the CHANGELOG entry for the fonts config

---

CHANGELOG.md
package-lock.json

populate release date and fix `package-lock.json` versions

populate release date and fix package-lock.json versions

---

CHANGELOG.md

use the correct version number for the next release

use the correct version number for the next release

---

CHANGELOG.md
packages/components/header/_header.scss

Search input focus state style (desktop): fix border width.
Closes https://github.com/nhsuk/nhsuk-frontend/issues/768.

Search box tweak

---

CHANGELOG.md

populate release date for v5.2.0

populate release date for v5.2.0

---

package-lock.json
package.json

bump version and update dependencies

bump version and update dependencies

---

app/components/all.njk
app/components/card/card-group.njk
packages/components/card/README.md

Fix 'charities' spelling mistake

---

CHANGELOG.md
packages/components/card/template.njk

fix card component format

---

.github/workflows/create-beta-package.yml

New yml file to allow us to publish beta versions to npm from the beta branch.

added beta workflow

---

CHANGELOG.md
README.md
package.json

updated changelog, package-json and readme

---

.github/workflows/release.yml

A dependency update has broken the build under Node 12 so I've updated to Node 16.
I can't think of a reason that this would be a problem but welcome any feedback!

Run github action under node 16

---

package-lock.json
packages/components/tabs/tabs.test.js
tests/integration/__snapshots__/tabs.test.js.snap
tests/integration/tabs.test.js

Tabs tests - Initial dom setup

---

CHANGELOG.md

Update the CHANGELOG with the release date for v6.2.0

---

CHANGELOG.md

Update CHANGELOG with release date for v7.

Update CHANGELOG with release date

---

app/components/tabs/index.njk
packages/components/tabs/README.md

Update content of the readme to be same as the example page, and tidy up the formatting of the macro.

Update formatting and content of the tabs component

---

package-lock.json
package.json

Update package json for release 8.1.0

Update package json for release 8.1.0

---

azure-pipelines.yml

Adding review environments in Azure DevOps for testing purposes.

Add azure pipeline for connection to review environments

---

packages/components/header/_header.scss
packages/components/header/template.njk

https://nhsd-jira.digital.nhs.uk/browse/TM-3235

Ensure that headers are aligned to expected standards

---

CHANGELOG.md

Fix: the changelog entry in #979 was added to the previous release rather than the unreleased section.

Fix changelog: Move bugfix entry to the right spot

---

packages/core/settings/_colours.scss

See https://sass-lang.com/documentation/breaking-changes/

Remove deprecated percentage syntax

---

CHANGELOG.md

Updates the changelog to describe the breaking changes in [Make it easier to set date values](https://github.com/nhsuk/nhsuk-frontend/pull/994].

Update changelog with description of date input changes

---

CHANGELOG.md

Fix breadcrumb 1px bug changelog

---

.github/workflows/pull-request.yml

Updates to latest version as using v2 now shows a depreciation message.

Update actions/checkout workflow to v4

---

.github/workflows/release.yml

PIn ubuntu to 22

---

package.json

This is just a convenience script for running all 3 of the other code style fixing scripts.

Add lint:fix script

---

packages/components/header/macro-options.json

Updates macro options for header using the new `macro-options.json`.
Think I’ve caught everything, but would appreciate a double-checking!
Part of #1058

Update macro options for new header

---

CHANGELOG.md
packages/nhsuk-frontend/src/nhsuk/common/index.mjs
packages/nhsuk-frontend/src/nhsuk/components/tabs/_index.scss
packages/nhsuk-frontend/src/nhsuk/components/tabs/tabs.jsdom.test.mjs
packages/nhsuk-frontend/src/nhsuk/components/tabs/tabs.mjs
packages/nhsuk-frontend/src/nhsuk/core/_nhsuk-frontend-properties.scss
shared/helpers/jest/environment/jest.jsdom.setup.mjs

Copies https://github.com/alphagov/govuk-frontend/pull/4562 from GOV.UK Frontend and closes https://github.com/nhsuk/nhsuk-frontend/issues/1476

Fix tabs component JavaScript to use `$nhsuk-breakpoints` option

---

CHANGELOG.md
packages/nhsuk-frontend-review/src/examples/components-in-details.njk
packages/nhsuk-frontend-review/src/index.njk
packages/nhsuk-frontend/src/nhsuk/components/checkboxes/_index.scss

Fix a visual bug with checkboxes inside a details component

---

CHANGELOG.md
packages/nhsuk-frontend/src/nhsuk/template.njk

See https://github.com/alphagov/govuk-frontend/pull/4434

Remove `X-UA-Compatible` meta tag

---

CHANGELOG.md
packages/nhsuk-frontend/src/nhsuk/core/settings/_warnings.scss

Quick PR to fix some issues following the v10.0.0 release

Fix typos in v10.0.0 release guidance etc
